module.exports = {
  content: [
    "./src/**/*.{js,jsx,ts,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        'alabaster': "#F1ECDE",
        'honeydew': "#CDE4DB",
        'tumbleweed': "#D1A783",
        'emerald': "#40916C",
        'green': "#1F4A38",
        'linen': "#FAF5E7",
        'sand': "#F5ECD6",
        'neonpink' : "#FF34A0",
        'lightblue' : "#D9F2F6",
        'navy' : "#03008C",
        'darkblue' : "#02005C",
        'indigo' : "#010029",
        'darkpurple' : "#14113E",
        'pastelpurple' : "#D3CCEF",
        'pinkpurple' : "#C2ADFF",
        'blue' : "#1B16F2",
        'pacificblue' : "#00B7FF",
        'pastelyellow' : "#FFF2AB",
        'yellow' : "#FAE368",
        'mustard' : "#D3A52D",
        'pastelpink' : "#FFADCC",
        'pink' : "#EA74A1",
        'darkpink' : "#A63C65",
        'pastelcoral' : "#FFD3C9",
        'coral' : "#F9A084",
        'orange' : "#F6795D",
        'brightblue': "#D9F2F7",
        'navy': "#293280",
        'brightyellow': "#fff2ab",
        'peach': "#f6795d",
      }
    },
  },
  plugins: [],
}